<?php

namespace Database\Seeders;

use App\Models\Permissions\Permission;
use App\Models\Roles\Role;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

/**
 * NOTE: If delete permission, make sure delete also at `syncRolesPermissions` method
 */
class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->createRoleIfNotExist();
        $this->createAndDeletePermission();
        $this->syncRolesPermissions();
    }

    private function createRoleIfNotExist()
    {
        $roles = collect([
            [
                'name' => 'superadmin',
                'display_name' => 'Superadmin',
                'description' => 'Control and monitor all system functionality',
            ],
            [
                'name' => 'user',
                'display_name' => 'User',
                'description' => 'A normal user who can fill the form',
            ],
            [
                'name' => 'client',
                'display_name' => 'Client',
                'description' => 'User who uses service features and can submit project testimonials.',
            ],
            [
                'name' => 'student',
                'display_name' => 'Student',
                'description' => 'User enrolled in courses, can access course materials and give feedback.',
            ],
            [
                'name' => 'partner',
                'display_name' => 'Partner',
                'description' => 'External collaborator or business partner with specific access.',
            ],
            [
                'name' => 'instructor',
                'display_name' => 'Instructor',
                'description' => 'External instructor with specific access.',
            ],
        ]);

        // Create role if not exist yet
        foreach ($roles as $role) {
            if (!Role::where('name', $role['name'])->exists()) {
                Role::create([
                    'name' => $role['name'],
                    'display_name' => $role['display_name'],
                    'description' => $role['description'],
                ]);
            }
        }
    }

    private function createAndDeletePermission()
    {
        $permissions = $this->permissions();

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(
                ['name' => $permission['name']],
                [
                    'display_name' => $permission['display_name'], 'group' => $permission['group'],
                    'description' => $permission['description']
                ]
            );
        }

        // Delete permission not in seeder array
        $unusedPermissions = Permission::whereNotIn('name', $permissions->pluck('name'))->get();
        foreach ($unusedPermissions as $unusedPermission) {
            $unusedPermission->delete();
        }
    }

    private function syncRolesPermissions()
    {
        $roles_permissions = [
            'superadmin' => [
                'my-account',
                'change-password',
                'change-email',
                'change-username',
                'my-activities',
                'recent-sessions',
                'all-user-activities',
                'all-user-sessions',
                'browse-roles',
                'read-roles',
                'edit-roles',
                'add-roles',
                'delete-roles',
                'browse-permissions',
                'read-permissions',
                'browse-users',
                'read-users',
                'edit-users',
                'add-users',
                'delete-users',
                // 'browse-forms',
                'read-forms',
                'edit-forms',
                'add-forms',
                'delete-forms',
                'browse-groups',
                'read-groups',
                'edit-groups',
                'add-groups',
                'delete-groups',
                'browse-form-types',
                'read-form-types',
                'edit-form-types',
                'add-form-types',
                'delete-form-types',
                'browse-notifications',
                'read-notifications',
                'edit-notifications',
                'delete-notifications',
                // 'browse-submissions',
                'read-submissions',
                'edit-submissions',
                'add-submissions',
                'delete-submissions',
                'process-submissions',
                'manage-workflow-processes',
                'browse-settings',
                'edit-settings',
                'browse-abouts',
                'read-abouts',
                'edit-abouts',
                'add-abouts',
                'delete-abouts',
                'browse-events',
                'read-events',
                'edit-events',
                'add-events',
                'delete-events',
                'browse-articles',
                'read-articles',
                'edit-articles',
                'add-articles',
                'delete-articles',
                'browse-services',
                'read-services',
                'edit-services',
                'add-services',
                'delete-services',
                'browse-projects',
                'read-projects',
                'edit-projects',
                'add-projects',
                'delete-projects',
                'browse-testimonies',
                'read-testimonies',
                'edit-testimonies',
                'add-testimonies',
                'delete-testimonies',
                'browse-tools',
                'read-tools',
                'edit-tools',
                'add-tools',
                'delete-tools',
                'browse-courses',
                'read-courses',
                'edit-courses',
                'add-courses',
                'delete-courses',
                'browse-contents',
                'read-contents',
                'edit-contents',
                'add-contents',
                'delete-contents',
                'browse-podcasts',
                'read-podcasts',
                'edit-podcasts',
                'add-podcasts',
                'delete-podcasts',
                'browse-newsletters',
                'read-newsletters',
                'edit-newsletters',
                'add-newsletters',
                'delete-newsletters',
                'browse-species',
                'read-species',
                'edit-species',
                'add-species',
                'delete-species',
                'browse-breeds',
                'read-breeds',
                'edit-breeds',
                'add-breeds',
                'delete-breeds',
                'browse-enclosures',
                'read-enclosures',
                'edit-enclosures',
                'add-enclosures',
                'delete-enclosures',
                'browse-animals',
                'read-animals',
                'edit-animals',
                'add-animals',
                'delete-animals',
                'browse-animal-groups',
                'read-animal-groups',
                'edit-animal-groups',
                'add-animal-groups',
                'delete-animal-groups',
                'browse-barcodes',
                'read-barcodes',
                'edit-barcodes',
                'add-barcodes',
                'delete-barcodes',
                'scan-barcodes',
                'browse-feedings',
                'read-feedings',
                'edit-feedings',
                'add-feedings',
                'delete-feedings',
                'browse-withdrawals',
                'read-withdrawals',
                'edit-withdrawals',
                'add-withdrawals',
                'delete-withdrawals',
                'browse-measurements',
                'read-measurements',
                'edit-measurements',
                'add-measurements',
                'delete-measurements',
                'browse-mortalities',
                'read-mortalities',
                'edit-mortalities',
                'add-mortalities',
                'delete-mortalities',
                'browse-treatments',
                'read-treatments',
                'edit-treatments',
                'add-treatments',
                'delete-treatments',
                'browse-eggs',
                'read-eggs',
                'edit-eggs',
                'add-eggs',
                'delete-eggs',
                'browse-hatches',
                'read-hatches',
                'edit-hatches',
                'add-hatches',
                'delete-hatches',
                'browse-purchases',
                'read-purchases',
                'edit-purchases',
                'add-purchases',
                'delete-purchases',
                'browse-sales',
                'read-sales',
                'edit-sales',
                'add-sales',
                'delete-sales',
                'browse-transaction-categories',
                'read-transaction-categories',
                'edit-transaction-categories',
                'add-transaction-categories',
                'delete-transaction-categories',
                'browse-transactions',
                'read-transactions',
                'edit-transactions',
                'add-transactions',
                'delete-transactions',
                'browse-devices',
                'read-devices',
                'edit-devices',
                'add-devices',
                'delete-devices',
                'browse-sensors',
                'read-sensors',
                'edit-sensors',
                'add-sensors',
                'delete-sensors',
                'browse-sensors',
                'read-sensors',
                'edit-sensors',
                'add-sensors',
                'delete-sensors',
                'browse-readings',
                'read-readings',
                'edit-readings',
                'add-readings',
                'delete-readings',
                'browse-alerts',
                'read-alerts',
                'edit-alerts',
                'add-alerts',
                'delete-alerts',
                'browse-alerts',
                'read-alerts',
                'edit-alerts',
                'add-alerts',
                'delete-alerts',
                'browse-alert-rules',
                'read-alert-rules',
                'edit-alert-rules',
                'add-alert-rules',
                'delete-alert-rules',
                'browse-inventory-items',
                'read-inventory-items',
                'edit-inventory-items',
                'add-inventory-items',
                'delete-inventory-items',
                'browse-inventory-movements',
                'read-inventory-movements',
                'edit-inventory-movements',
                'add-inventory-movements',
                'delete-inventory-movements',
                'browse-farms',
                'read-farms',
                'edit-farms',
                'add-farms',
                'delete-farms',
                'browse-workflow-template-types',
                'read-workflow-template-types',
                'edit-workflow-template-types',
                'add-workflow-template-types',
                'delete-workflow-template-types',
                'browse-workflow-templates',
                'read-workflow-templates',
                'edit-workflow-templates',
                'add-workflow-templates',
                'delete-workflow-templates',
                'browse-bot-types',
                'read-bot-types',
                'edit-bot-types',
                'add-bot-types',
                'delete-bot-types',
                'browse-bots',
                'read-bots',
                'edit-bots',
                'add-bots',
                'delete-bots',
                'browse-bookings',
                'read-bookings',
                'edit-bookings',
                'add-bookings',
                'delete-bookings',
                'browse-products',
                'read-products',
                'edit-products',
                'add-products',
                'delete-products',
                'browse-product-digitals',
                'read-product-digitals',
                'edit-product-digitals',
                'add-product-digitals',
                'delete-product-digitals',
                'browse-product-physicals',
                'read-product-physicals',
                'edit-product-physicals',
                'add-product-physicals',
                'delete-product-physicals',
                'browse-product-appointments',
                'read-product-appointments',
                'edit-product-appointments',
                'add-product-appointments',
                'delete-product-appointments',
                'browse-companies',
                'read-companies',
                'edit-companies',
                'add-companies',
                'delete-companies',
                'browse-brands',
                'read-brands',
                'edit-brands',
                'add-brands',
                'delete-brands',
                'browse-brand-categories',
                'read-brand-categories',
                'edit-brand-categories',
                'add-brand-categories',
                'delete-brand-categories',
                'browse-faqs',
                'read-faqs',
                'edit-faqs',
                'add-faqs',
                'delete-faqs',
            ],
            'user' => [
                'my-account',
                'change-password',
                'change-email',
                'change-username',
                'my-activities',
                'recent-sessions',
                'browse-notifications',
                'read-notifications',
                'edit-notifications',
                'delete-notifications',
                'browse-submissions',
                'add-submissions',
            ],
            'client' => [
                'my-account',
                'change-password',
                'change-email',
                'change-username',
                'my-activities',
                'recent-sessions',
                'browse-notifications',
                'read-notifications',
                'edit-notifications',
                'delete-notifications',
                'browse-submissions',
                'add-submissions',
            ],
            'student' => [
                'my-account',
                'change-password',
                'change-email',
                'change-username',
                'my-activities',
                'recent-sessions',
                'browse-notifications',
                'read-notifications',
                'edit-notifications',
                'delete-notifications',
                'browse-submissions',
                'add-submissions',
            ],
            'partner' => [
                'my-account',
                'change-password',
                'change-email',
                'change-username',
                'my-activities',
                'recent-sessions',
                'browse-notifications',
                'read-notifications',
                'edit-notifications',
                'delete-notifications',
                'browse-submissions',
                'add-submissions',
            ],
        ];

        foreach ($roles_permissions as $index => $value) {
            $role = Role::findByName($index);
            $role->syncPermissions($value);
        }
    }

    public function groups(): Collection
    {
        return collect([
            'profile' => 'profile',
            'roles' => 'roles',
            'permissions' => 'permissions',
            'activity_log' => 'activity_log',
            'authentication_log' => 'authentication_log',
            'users' => 'users',
            'forms' => 'forms',
            'groups' => 'groups',
            'form_types' => 'form_types',
            'notifications' => 'notifications',
            'form_submissions' => 'form_submissions',
            'workflow_processes' => 'workflow_processes',
            'settings' => 'settings',
            'abouts' => 'abouts',
            'events' => 'events',
            'articles' => 'articles',
            'services' => 'services',
            'projects' => 'projects',
            'testimonies' => 'testimonies',
            'tools' => 'tools',
            'courses' => 'courses',
            'contents' => 'contents',
            'podcasts' => 'podcasts',
            'newsletters' => 'newsletters',
            'species' => 'species',
            'breeds' => 'breeds',
            'enclosures' => 'enclosures',
            'animals' => 'animals',
            'animal-groups' => 'animal-groups',
            'barcodes' => 'barcodes',
            'feedings' => 'feedings',
            'withdrawals' => 'withdrawals',
            'measurements' => 'measurements',
            'mortalities' => 'mortalities',
            'treatments' => 'treatments',
            'eggs' => 'eggs',
            'hatches' => 'hatches',
            'purchases' => 'purchases',
            'sales' => 'sales',
            'transaction-categories' => 'transaction-categories',
            'transactions' => 'transactions',
            'devices' => 'devices',
            'sensors' => 'sensors',
            'readings' => 'readings',
            'alerts' => 'alerts',
            'alert-rules' => 'alert-rules',
            'inventory-items' => 'inventory-items',
            'inventory-movements' => 'inventory-movements',
            'farms' => 'farms',
            'workflow-template-types' => 'workflow-template-types',
            'workflow-templates' => 'workflow-templates',
            'bot-types' => 'bot-types',
            'bots' => 'bots',
            'bookings' => 'bookings',
            'faqs' => 'faqs',
            'companies' => 'companies',
            'products' => 'products',
            'product-digitals' => 'product-digitals',
            'product-physicals' => 'product-physicals',
            'product-appointments' => 'product-appointments',
            'brands' => 'brands',
            'brand-categories' => 'brand-categories',
        ]);
    }

    public function permissions(): Collection
    {
        $groups = $this->groups();

        return collect([
            [
                'name' => 'my-account',
                'display_name' => 'my_account',
                'group' => $groups['profile'],
                'description' => 'view_profile_information',
            ],
            [
                'name' => 'change-password',
                'display_name' => 'change_password',
                'group' => $groups['profile'],
                'description' => 'change_user_password',
            ],
            [
                'name' => 'change-email',
                'display_name' => 'change_email',
                'group' => $groups['profile'],
                'description' => 'change_user_email',
            ],
            [
                'name' => 'change-username',
                'display_name' => 'change_username',
                'group' => $groups['profile'],
                'description' => 'change_current_username',
            ],
            [
                'name' => 'my-activities',
                'display_name' => 'my_activities',
                'group' => $groups['profile'],
                'description' => 'view_all_current_user_activity',
            ],
            [
                'name' => 'recent-sessions',
                'display_name' => 'recent_sessions',
                'group' => $groups['profile'],
                'description' => 'view_all_recent_sessions_for_the_current_user',
            ],
            [
                'name' => 'all-user-activities',
                'display_name' => 'all_user_activities',
                'group' => $groups['activity_log'],
                'description' => 'list_of_all_user_activities',
            ],
            [
                'name' => 'all-user-sessions',
                'display_name' => 'all_user_sessions',
                'group' => $groups['authentication_log'],
                'description' => 'list_of_all_user_sessions',
            ],
            [
                'name' => 'browse-roles',
                'display_name' => 'browse_roles',
                'group' => $groups['roles'],
                'description' => 'list_of_all_role',
            ],
            [
                'name' => 'read-roles',
                'display_name' => 'read_roles',
                'group' => $groups['roles'],
                'description' => 'read_the_selected_role',
            ],
            [
                'name' => 'edit-roles',
                'display_name' => 'edit_roles',
                'group' => $groups['roles'],
                'description' => 'edit_the_selected_role',
            ],
            [
                'name' => 'add-roles',
                'display_name' => 'add_roles',
                'group' => $groups['roles'],
                'description' => 'add_specific_role',
            ],
            [
                'name' => 'delete-roles',
                'display_name' => 'delete_roles',
                'group' => $groups['roles'],
                'description' => 'delete_the_selected_role',
            ],
            [
                'name' => 'browse-permissions',
                'display_name' => 'browse_permissions',
                'group' => $groups['permissions'],
                'description' => 'list_of_all_permission',
            ],
            [
                'name' => 'read-permissions',
                'display_name' => 'read_permissions',
                'group' => $groups['permissions'],
                'description' => 'read_the_selected_permission',
            ],
            [
                'name' => 'browse-users',
                'display_name' => 'browse_users',
                'group' => $groups['users'],
                'description' => 'list_of_all_user',
            ],
            [
                'name' => 'read-users',
                'display_name' => 'read_users',
                'group' => $groups['users'],
                'description' => 'read_the_selected_user',
            ],
            [
                'name' => 'edit-users',
                'display_name' => 'edit_users',
                'group' => $groups['users'],
                'description' => 'edit_account_for_selected_user',
            ],
            [
                'name' => 'add-users',
                'display_name' => 'add_users',
                'group' => $groups['users'],
                'description' => 'add_account_for_user',
            ],
            [
                'name' => 'delete-users',
                'display_name' => 'delete_users',
                'group' => $groups['users'],
                'description' => 'delete_account_for_selected_user',
            ],
            [
                'name' => 'browse-forms',
                'display_name' => 'browse_forms',
                'group' => $groups['forms'],
                'description' => 'list_of_all_form',
            ],
            [
                'name' => 'read-forms',
                'display_name' => 'read_forms',
                'group' => $groups['forms'],
                'description' => 'read_the_selected_form',
            ],
            [
                'name' => 'edit-forms',
                'display_name' => 'edit_forms',
                'group' => $groups['forms'],
                'description' => 'edit_the_selected_form',
            ],
            [
                'name' => 'add-forms',
                'display_name' => 'add_forms',
                'group' => $groups['forms'],
                'description' => 'add_new_form',
            ],
            [
                'name' => 'delete-forms',
                'display_name' => 'delete_forms',
                'group' => $groups['forms'],
                'description' => 'delete_the_selected_form',
            ],
            [
                'name' => 'browse-groups',
                'display_name' => 'browse_groups',
                'group' => $groups['groups'],
                'description' => 'list_of_all_group',
            ],
            [
                'name' => 'read-groups',
                'display_name' => 'read_group',
                'group' => $groups['groups'],
                'description' => 'read_the_selected_group',
            ],
            [
                'name' => 'edit-groups',
                'display_name' => 'edit_group',
                'group' => $groups['groups'],
                'description' => 'edit_the_selected_group',
            ],
            [
                'name' => 'add-groups',
                'display_name' => 'add_groups',
                'group' => $groups['groups'],
                'description' => 'add_new_group',
            ],
            [
                'name' => 'delete-groups',
                'display_name' => 'delete_groups',
                'group' => $groups['groups'],
                'description' => 'delete_the_selected_group',
            ],
            [
                'name' => 'browse-form-types',
                'display_name' => 'browse_form_types',
                'group' => $groups['form_types'],
                'description' => 'list_of_all_form_type',
            ],
            [
                'name' => 'read-form-types',
                'display_name' => 'read_form_types',
                'group' => $groups['form_types'],
                'description' => 'read_the_selected_form_type',
            ],
            [
                'name' => 'edit-form-types',
                'display_name' => 'edit_form_types',
                'group' => $groups['form_types'],
                'description' => 'edit_the_selected_form_type',
            ],
            [
                'name' => 'add-form-types',
                'display_name' => 'add_form_types',
                'group' => $groups['form_types'],
                'description' => 'add_new_form_type',
            ],
            [
                'name' => 'delete-form-types',
                'display_name' => 'delete_form_types',
                'group' => $groups['form_types'],
                'description' => 'delete_the_selected_form_type',
            ],
            [
                'name' => 'browse-notifications',
                'display_name' => 'browse_notifications',
                'group' => $groups['notifications'],
                'description' => 'list_of_all_notification',
            ],
            [
                'name' => 'read-notifications',
                'display_name' => 'read_notifications',
                'group' => $groups['notifications'],
                'description' => 'read_the_selected_notification',
            ],
            [
                'name' => 'edit-notifications',
                'display_name' => 'edit_notifications',
                'group' => $groups['notifications'],
                'description' => 'edit_the_selected_notification',
            ],
            [
                'name' => 'delete-notifications',
                'display_name' => 'delete_notifications',
                'group' => $groups['notifications'],
                'description' => 'delete_the_selected_notification',
            ],
            [
                'name' => 'browse-submissions',
                'display_name' => 'browse_submissions',
                'group' => $groups['form_submissions'],
                'description' => 'list_of_all_form_submission',
            ],
            [
                'name' => 'read-submissions',
                'display_name' => 'read_submissions',
                'group' => $groups['form_submissions'],
                'description' => 'read_the_selected_form_submission',
            ],
            [
                'name' => 'edit-submissions',
                'display_name' => 'edit_submissions',
                'group' => $groups['form_submissions'],
                'description' => 'edit_the_selected_form_submission',
            ],
            [
                'name' => 'add-submissions',
                'display_name' => 'add_submissions',
                'group' => $groups['form_submissions'],
                'description' => 'add_new_form_submission',
            ],
            [
                'name' => 'delete-submissions',
                'display_name' => 'delete_submissions',
                'group' => $groups['form_submissions'],
                'description' => 'delete_the_selected_form_submission',
            ],
            [
                'name' => 'process-submissions',
                'display_name' => 'process_submissions',
                'group' => $groups['form_submissions'],
                'description' => 'list_of_users_who_can_manage_the_submission_process',
            ],
            [
                'name' => 'manage-workflow-processes',
                'display_name' => 'manage_workflow_processes',
                'group' => $groups['workflow_processes'],
                'description' => 'manage_workflow_process_for_the_form',
            ],
            [
                'name' => 'browse-settings',
                'display_name' => 'browse_settings',
                'group' => $groups['settings'],
                'description' => 'list_of_all_setting',
            ],
            [
                'name' => 'edit-settings',
                'display_name' => 'edit_settings',
                'group' => $groups['settings'],
                'description' => 'allows_managing_and_updating_system_settings',
            ],
            [
                'name' => 'browse-abouts',
                'display_name' => 'browse_abouts',
                'group' => $groups['abouts'],
                'description' => 'list_of_all_about',
            ],
            [
                'name' => 'read-abouts',
                'display_name' => 'read_abouts',
                'group' => $groups['abouts'],
                'description' => 'read_the_selected_about',
            ],
            [
                'name' => 'edit-abouts',
                'display_name' => 'edit_abouts',
                'group' => $groups['abouts'],
                'description' => 'edit_the_selected_about',
            ],
            [
                'name' => 'add-abouts',
                'display_name' => 'add_abouts',
                'group' => $groups['abouts'],
                'description' => 'add_new_about',
            ],
            [
                'name' => 'delete-abouts',
                'display_name' => 'delete_abouts',
                'group' => $groups['abouts'],
                'description' => 'delete_the_selected_about',
            ],
            [
                'name' => 'browse-events',
                'display_name' => 'browse_events',
                'group' => $groups['events'],
                'description' => 'list_of_all_event',
            ],
            [
                'name' => 'read-events',
                'display_name' => 'read_events',
                'group' => $groups['events'],
                'description' => 'read_the_selected_event',
            ],
            [
                'name' => 'edit-events',
                'display_name' => 'edit_events',
                'group' => $groups['events'],
                'description' => 'edit_the_selected_event',
            ],
            [
                'name' => 'add-events',
                'display_name' => 'add_events',
                'group' => $groups['events'],
                'description' => 'add_new_event',
            ],
            [
                'name' => 'delete-events',
                'display_name' => 'delete_events',
                'group' => $groups['events'],
                'description' => 'delete_the_selected_event',
            ],
            [
                'name' => 'browse-articles',
                'display_name' => 'browse_articles',
                'group' => $groups['articles'],
                'description' => 'list_of_all_article',
            ],
            [
                'name' => 'read-articles',
                'display_name' => 'read_articles',
                'group' => $groups['articles'],
                'description' => 'read_the_selected_article',
            ],
            [
                'name' => 'edit-articles',
                'display_name' => 'edit_articles',
                'group' => $groups['articles'],
                'description' => 'edit_the_selected_article',
            ],
            [
                'name' => 'add-articles',
                'display_name' => 'add_articles',
                'group' => $groups['articles'],
                'description' => 'add_new_article',
            ],
            [
                'name' => 'delete-articles',
                'display_name' => 'delete_articles',
                'group' => $groups['articles'],
                'description' => 'delete_the_selected_article',
            ],
            [
                'name' => 'browse-services',
                'display_name' => 'browse_services',
                'group' => $groups['services'],
                'description' => 'list_of_all_service',
            ],
            [
                'name' => 'read-services',
                'display_name' => 'read_services',
                'group' => $groups['services'],
                'description' => 'read_the_selected_service',
            ],
            [
                'name' => 'edit-services',
                'display_name' => 'edit_services',
                'group' => $groups['services'],
                'description' => 'edit_the_selected_service',
            ],
            [
                'name' => 'add-services',
                'display_name' => 'add_services',
                'group' => $groups['services'],
                'description' => 'add_new_service',
            ],
            [
                'name' => 'delete-services',
                'display_name' => 'delete_services',
                'group' => $groups['services'],
                'description' => 'delete_the_selected_service',
            ],
            [
                'name' => 'browse-projects',
                'display_name' => 'browse_projects',
                'group' => $groups['projects'],
                'description' => 'list_of_all_project',
            ],
            [
                'name' => 'read-projects',
                'display_name' => 'read_projects',
                'group' => $groups['projects'],
                'description' => 'read_the_selected_project',
            ],
            [
                'name' => 'edit-projects',
                'display_name' => 'edit_projects',
                'group' => $groups['projects'],
                'description' => 'edit_the_selected_project',
            ],
            [
                'name' => 'add-projects',
                'display_name' => 'add_projects',
                'group' => $groups['projects'],
                'description' => 'add_new_project',
            ],
            [
                'name' => 'delete-projects',
                'display_name' => 'delete_projects',
                'group' => $groups['projects'],
                'description' => 'delete_the_selected_project',
            ],
            [
                'name' => 'browse-testimonies',
                'display_name' => 'browse_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'list_of_all_testimony',
            ],
            [
                'name' => 'read-testimonies',
                'display_name' => 'read_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'read_the_selected_testimony',
            ],
            [
                'name' => 'edit-testimonies',
                'display_name' => 'edit_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'edit_the_selected_testimony',
            ],
            [
                'name' => 'add-testimonies',
                'display_name' => 'add_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'add_new_testimony',
            ],
            [
                'name' => 'delete-testimonies',
                'display_name' => 'delete_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'delete_the_selected_testimony',
            ],
            [
                'name' => 'browse-testimonies',
                'display_name' => 'browse_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'list_of_all_testimony',
            ],
            [
                'name' => 'read-testimonies',
                'display_name' => 'read_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'read_the_selected_testimony',
            ],
            [
                'name' => 'edit-testimonies',
                'display_name' => 'edit_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'edit_the_selected_testimony',
            ],
            [
                'name' => 'add-testimonies',
                'display_name' => 'add_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'add_new_testimony',
            ],
            [
                'name' => 'delete-testimonies',
                'display_name' => 'delete_testimonies',
                'group' => $groups['testimonies'],
                'description' => 'delete_the_selected_testimony',
            ],
            [
                'name' => 'browse-tools',
                'display_name' => 'browse_tools',
                'group' => $groups['tools'],
                'description' => 'list_of_all_tool',
            ],
            [
                'name' => 'read-tools',
                'display_name' => 'read_tools',
                'group' => $groups['tools'],
                'description' => 'read_the_selected_tool',
            ],
            [
                'name' => 'edit-tools',
                'display_name' => 'edit_tools',
                'group' => $groups['tools'],
                'description' => 'edit_the_selected_tool',
            ],
            [
                'name' => 'add-tools',
                'display_name' => 'add_tools',
                'group' => $groups['tools'],
                'description' => 'add_new_tool',
            ],
            [
                'name' => 'delete-tools',
                'display_name' => 'delete_tools',
                'group' => $groups['tools'],
                'description' => 'delete_the_selected_tool',
            ],
            [
                'name' => 'browse-courses',
                'display_name' => 'browse_courses',
                'group' => $groups['courses'],
                'description' => 'list_of_all_course',
            ],
            [
                'name' => 'read-courses',
                'display_name' => 'read_courses',
                'group' => $groups['courses'],
                'description' => 'read_the_selected_course',
            ],
            [
                'name' => 'edit-courses',
                'display_name' => 'edit_courses',
                'group' => $groups['courses'],
                'description' => 'edit_the_selected_course',
            ],
            [
                'name' => 'add-courses',
                'display_name' => 'add_courses',
                'group' => $groups['courses'],
                'description' => 'add_new_course',
            ],
            [
                'name' => 'delete-courses',
                'display_name' => 'delete_courses',
                'group' => $groups['courses'],
                'description' => 'delete_the_selected_course',
            ],
            [
                'name' => 'browse-contents',
                'display_name' => 'browse_contents',
                'group' => $groups['contents'],
                'description' => 'list_of_all_content',
            ],
            [
                'name' => 'read-contents',
                'display_name' => 'read_contents',
                'group' => $groups['contents'],
                'description' => 'read_the_selected_content',
            ],
            [
                'name' => 'edit-contents',
                'display_name' => 'edit_contents',
                'group' => $groups['contents'],
                'description' => 'edit_the_selected_content',
            ],
            [
                'name' => 'add-contents',
                'display_name' => 'add_contents',
                'group' => $groups['contents'],
                'description' => 'add_new_content',
            ],
            [
                'name' => 'delete-contents',
                'display_name' => 'delete_contents',
                'group' => $groups['contents'],
                'description' => 'delete_the_selected_content',
            ],
            [
                'name' => 'browse-contents',
                'display_name' => 'browse_contents',
                'group' => $groups['contents'],
                'description' => 'list_of_all_content',
            ],
            [
                'name' => 'read-contents',
                'display_name' => 'read_contents',
                'group' => $groups['contents'],
                'description' => 'read_the_selected_content',
            ],
            [
                'name' => 'edit-contents',
                'display_name' => 'edit_contents',
                'group' => $groups['contents'],
                'description' => 'edit_the_selected_content',
            ],
            [
                'name' => 'add-contents',
                'display_name' => 'add_contents',
                'group' => $groups['contents'],
                'description' => 'add_new_content',
            ],
            [
                'name' => 'delete-contents',
                'display_name' => 'delete_contents',
                'group' => $groups['contents'],
                'description' => 'delete_the_selected_content',
            ],
            [
                'name' => 'browse-podcasts',
                'display_name' => 'browse_podcasts',
                'group' => $groups['podcasts'],
                'description' => 'list_of_all_podcast',
            ],
            [
                'name' => 'read-podcasts',
                'display_name' => 'read_podcasts',
                'group' => $groups['podcasts'],
                'description' => 'read_the_selected_podcast',
            ],
            [
                'name' => 'edit-podcasts',
                'display_name' => 'edit_podcasts',
                'group' => $groups['podcasts'],
                'description' => 'edit_the_selected_podcast',
            ],
            [
                'name' => 'add-podcasts',
                'display_name' => 'add_podcasts',
                'group' => $groups['podcasts'],
                'description' => 'add_new_podcast',
            ],
            [
                'name' => 'delete-podcasts',
                'display_name' => 'delete_podcasts',
                'group' => $groups['podcasts'],
                'description' => 'delete_the_selected_podcast',
            ],
            [
                'name' => 'browse-newsletters',
                'display_name' => 'browse_newsletters',
                'group' => $groups['newsletters'],
                'description' => 'list_of_all_newsletter',
            ],
            [
                'name' => 'read-newsletters',
                'display_name' => 'read_newsletters',
                'group' => $groups['newsletters'],
                'description' => 'read_the_selected_newsletter',
            ],
            [
                'name' => 'edit-newsletters',
                'display_name' => 'edit_newsletters',
                'group' => $groups['newsletters'],
                'description' => 'edit_the_selected_newsletter',
            ],
            [
                'name' => 'add-newsletters',
                'display_name' => 'add_newsletters',
                'group' => $groups['newsletters'],
                'description' => 'add_new_newsletter',
            ],
            [
                'name' => 'delete-newsletters',
                'display_name' => 'delete_newsletters',
                'group' => $groups['newsletters'],
                'description' => 'delete_the_selected_newsletter',
            ],

            // SPECIES
            ['name'=>'browse-species','display_name'=>'browse_species','group'=>$groups['species'],'description'=>'list_of_all_species'],
            ['name'=>'read-species','display_name'=>'read_species','group'=>$groups['species'],'description'=>'read_the_selected_species'],
            ['name'=>'edit-species','display_name'=>'edit_species','group'=>$groups['species'],'description'=>'edit_the_selected_species'],
            ['name'=>'add-species','display_name'=>'add_species','group'=>$groups['species'],'description'=>'add_new_species'],
            ['name'=>'delete-species','display_name'=>'delete_species','group'=>$groups['species'],'description'=>'delete_the_selected_species'],

            // BREEDS
            ['name'=>'browse-breeds','display_name'=>'browse_breeds','group'=>$groups['breeds'],'description'=>'list_of_all_breeds'],
            ['name'=>'read-breeds','display_name'=>'read_breeds','group'=>$groups['breeds'],'description'=>'read_the_selected_breed'],
            ['name'=>'edit-breeds','display_name'=>'edit_breeds','group'=>$groups['breeds'],'description'=>'edit_the_selected_breed'],
            ['name'=>'add-breeds','display_name'=>'add_breeds','group'=>$groups['breeds'],'description'=>'add_new_breed'],
            ['name'=>'delete-breeds','display_name'=>'delete_breeds','group'=>$groups['breeds'],'description'=>'delete_the_selected_breed'],

            // ENCLOSURES
            ['name'=>'browse-enclosures','display_name'=>'browse_enclosures','group'=>$groups['enclosures'],'description'=>'list_of_all_enclosures'],
            ['name'=>'read-enclosures','display_name'=>'read_enclosures','group'=>$groups['enclosures'],'description'=>'read_the_selected_enclosure'],
            ['name'=>'edit-enclosures','display_name'=>'edit_enclosures','group'=>$groups['enclosures'],'description'=>'edit_the_selected_enclosure'],
            ['name'=>'add-enclosures','display_name'=>'add_enclosures','group'=>$groups['enclosures'],'description'=>'add_new_enclosure'],
            ['name'=>'delete-enclosures','display_name'=>'delete_enclosures','group'=>$groups['enclosures'],'description'=>'delete_the_selected_enclosure'],

            // ANIMALS
            ['name'=>'browse-animals','display_name'=>'browse_animals','group'=>$groups['animals'],'description'=>'list_of_all_animals'],
            ['name'=>'read-animals','display_name'=>'read_animals','group'=>$groups['animals'],'description'=>'read_the_selected_animal'],
            ['name'=>'edit-animals','display_name'=>'edit_animals','group'=>$groups['animals'],'description'=>'edit_the_selected_animal'],
            ['name'=>'add-animals','display_name'=>'add_animals','group'=>$groups['animals'],'description'=>'add_new_animal'],
            ['name'=>'delete-animals','display_name'=>'delete_animals','group'=>$groups['animals'],'description'=>'delete_the_selected_animal'],

            // ANIMAL GROUPS
            ['name'=>'browse-animal-groups','display_name'=>'browse_animal_groups','group'=>$groups['animal-groups'],'description'=>'list_of_all_animal_groups'],
            ['name'=>'read-animal-groups','display_name'=>'read_animal_groups','group'=>$groups['animal-groups'],'description'=>'read_the_selected_animal_group'],
            ['name'=>'edit-animal-groups','display_name'=>'edit_animal_groups','group'=>$groups['animal-groups'],'description'=>'edit_the_selected_animal_group'],
            ['name'=>'add-animal-groups','display_name'=>'add_animal_groups','group'=>$groups['animal-groups'],'description'=>'add_new_animal_group'],
            ['name'=>'delete-animal-groups','display_name'=>'delete_animal_groups','group'=>$groups['animal-groups'],'description'=>'delete_the_selected_animal_group'],

            // BARCODES
            ['name'=>'browse-barcodes','display_name'=>'browse_barcodes','group'=>$groups['barcodes'],'description'=>'list_of_all_barcodes'],
            ['name'=>'read-barcodes','display_name'=>'read_barcodes','group'=>$groups['barcodes'],'description'=>'read_the_selected_barcode'],
            ['name'=>'edit-barcodes','display_name'=>'edit_barcodes','group'=>$groups['barcodes'],'description'=>'edit_the_selected_barcode'],
            ['name'=>'add-barcodes','display_name'=>'add_barcodes','group'=>$groups['barcodes'],'description'=>'add_new_barcode'],
            ['name'=>'delete-barcodes','display_name'=>'delete_barcodes','group'=>$groups['barcodes'],'description'=>'delete_the_selected_barcode'],
            ['name'=>'scan-barcodes','display_name'=>'scan_barcodes','group'=>$groups['barcodes'],'description'=>'scanner_barcode'],

            // FEEDINGS
            ['name'=>'browse-feedings','display_name'=>'browse_feedings','group'=>$groups['feedings'],'description'=>'list_of_all_feedings'],
            ['name'=>'read-feedings','display_name'=>'read_feedings','group'=>$groups['feedings'],'description'=>'read_the_selected_feeding'],
            ['name'=>'edit-feedings','display_name'=>'edit_feedings','group'=>$groups['feedings'],'description'=>'edit_the_selected_feeding'],
            ['name'=>'add-feedings','display_name'=>'add_feedings','group'=>$groups['feedings'],'description'=>'add_new_feeding'],
            ['name'=>'delete-feedings','display_name'=>'delete_feedings','group'=>$groups['feedings'],'description'=>'delete_the_selected_feeding'],

            // WITHDRAWAL
            ['name'=>'browse-withdrawals','display_name'=>'browse_withdrawals','group'=>$groups['withdrawals'],'description'=>'list_of_all_withdrawals'],
            ['name'=>'read-withdrawals','display_name'=>'read_withdrawals','group'=>$groups['withdrawals'],'description'=>'read_the_selected_withdrawal'],
            ['name'=>'edit-withdrawals','display_name'=>'edit_withdrawals','group'=>$groups['withdrawals'],'description'=>'edit_the_selected_withdrawal'],
            ['name'=>'add-withdrawals','display_name'=>'add_withdrawals','group'=>$groups['withdrawals'],'description'=>'add_new_withdrawal'],
            ['name'=>'delete-withdrawals','display_name'=>'delete_withdrawals','group'=>$groups['withdrawals'],'description'=>'delete_the_selected_withdrawal'],

            // MEASUREMENTS
            ['name'=>'browse-measurements','display_name'=>'browse_measurements','group'=>$groups['measurements'],'description'=>'list_of_all_measurements'],
            ['name'=>'read-measurements','display_name'=>'read_measurements','group'=>$groups['measurements'],'description'=>'read_the_selected_measurement'],
            ['name'=>'edit-measurements','display_name'=>'edit_measurements','group'=>$groups['measurements'],'description'=>'edit_the_selected_measurement'],
            ['name'=>'add-measurements','display_name'=>'add_measurements','group'=>$groups['measurements'],'description'=>'add_new_measurement'],
            ['name'=>'delete-measurements','display_name'=>'delete_measurements','group'=>$groups['measurements'],'description'=>'delete_the_selected_measurement'],

            // MORTALITIES
            ['name'=>'browse-mortalities','display_name'=>'browse_mortalities','group'=>$groups['mortalities'],'description'=>'list_of_all_mortality_records'],
            ['name'=>'read-mortalities','display_name'=>'read_mortalities','group'=>$groups['mortalities'],'description'=>'read_the_selected_mortality_record'],
            ['name'=>'edit-mortalities','display_name'=>'edit_mortalities','group'=>$groups['mortalities'],'description'=>'edit_the_selected_mortality_record'],
            ['name'=>'add-mortalities','display_name'=>'add_mortalities','group'=>$groups['mortalities'],'description'=>'add_new_mortality_record'],
            ['name'=>'delete-mortalities','display_name'=>'delete_mortalities','group'=>$groups['mortalities'],'description'=>'delete_the_selected_mortality_record'],

            // TREATMENTS
            ['name'=>'browse-treatments','display_name'=>'browse_treatments','group'=>$groups['treatments'],'description'=>'list_of_all_treatments'],
            ['name'=>'read-treatments','display_name'=>'read_treatments','group'=>$groups['treatments'],'description'=>'read_the_selected_treatment'],
            ['name'=>'edit-treatments','display_name'=>'edit_treatments','group'=>$groups['treatments'],'description'=>'edit_the_selected_treatment'],
            ['name'=>'add-treatments','display_name'=>'add_treatments','group'=>$groups['treatments'],'description'=>'add_new_treatment'],
            ['name'=>'delete-treatments','display_name'=>'delete_treatments','group'=>$groups['treatments'],'description'=>'delete_the_selected_treatment'],

            // EGGS (egg collections)
            ['name'=>'browse-eggs','display_name'=>'browse_eggs','group'=>$groups['eggs'],'description'=>'list_of_all_egg_collections'],
            ['name'=>'read-eggs','display_name'=>'read_eggs','group'=>$groups['eggs'],'description'=>'read_the_selected_egg_collection'],
            ['name'=>'edit-eggs','display_name'=>'edit_eggs','group'=>$groups['eggs'],'description'=>'edit_the_selected_egg_collection'],
            ['name'=>'add-eggs','display_name'=>'add_eggs','group'=>$groups['eggs'],'description'=>'add_new_egg_collection'],
            ['name'=>'delete-eggs','display_name'=>'delete_eggs','group'=>$groups['eggs'],'description'=>'delete_the_selected_egg_collection'],

            // HATCH (incubation)
            ['name'=>'browse-hatches','display_name'=>'browse_hatches','group'=>$groups['hatches'],'description'=>'list_of_all_hatch_records'],
            ['name'=>'read-hatches','display_name'=>'read_hatches','group'=>$groups['hatches'],'description'=>'read_the_selected_hatch_record'],
            ['name'=>'edit-hatches','display_name'=>'edit_hatches','group'=>$groups['hatches'],'description'=>'edit_the_selected_hatch_record'],
            ['name'=>'add-hatches','display_name'=>'add_hatches','group'=>$groups['hatches'],'description'=>'add_new_hatch_record'],
            ['name'=>'delete-hatches','display_name'=>'delete_hatches','group'=>$groups['hatches'],'description'=>'delete_the_selected_hatch_record'],

            // PURCHASES
            ['name'=>'browse-purchases','display_name'=>'browse_purchases','group'=>$groups['purchases'],'description'=>'list_of_all_purchases'],
            ['name'=>'read-purchases','display_name'=>'read_purchases','group'=>$groups['purchases'],'description'=>'read_the_selected_purchase'],
            ['name'=>'edit-purchases','display_name'=>'edit_purchases','group'=>$groups['purchases'],'description'=>'edit_the_selected_purchase'],
            ['name'=>'add-purchases','display_name'=>'add_purchases','group'=>$groups['purchases'],'description'=>'add_new_purchase'],
            ['name'=>'delete-purchases','display_name'=>'delete_purchases','group'=>$groups['purchases'],'description'=>'delete_the_selected_purchase'],

            // SALES
            ['name'=>'browse-sales','display_name'=>'browse_sales','group'=>$groups['sales'],'description'=>'list_of_all_sales'],
            ['name'=>'read-sales','display_name'=>'read_sales','group'=>$groups['sales'],'description'=>'read_the_selected_sale'],
            ['name'=>'edit-sales','display_name'=>'edit_sales','group'=>$groups['sales'],'description'=>'edit_the_selected_sale'],
            ['name'=>'add-sales','display_name'=>'add_sales','group'=>$groups['sales'],'description'=>'add_new_sale'],
            ['name'=>'delete-sales','display_name'=>'delete_sales','group'=>$groups['sales'],'description'=>'delete_the_selected_sale'],

            // TRANSACTION CATEGORIES
            ['name'=>'browse-transaction-categories','display_name'=>'browse_transaction_categories','group'=>$groups['transaction-categories'],'description'=>'list_of_all_transaction_categories'],
            ['name'=>'read-transaction-categories','display_name'=>'read_transaction_categories','group'=>$groups['transaction-categories'],'description'=>'read_the_selected_transaction_category'],
            ['name'=>'edit-transaction-categories','display_name'=>'edit_transaction_categories','group'=>$groups['transaction-categories'],'description'=>'edit_the_selected_transaction_category'],
            ['name'=>'add-transaction-categories','display_name'=>'add_transaction_categories','group'=>$groups['transaction-categories'],'description'=>'add_new_transaction_category'],
            ['name'=>'delete-transaction-categories','display_name'=>'delete_transaction_categories','group'=>$groups['transaction-categories'],'description'=>'delete_the_selected_transaction_category'],

            // TRANSACTIONS
            ['name'=>'browse-transactions','display_name'=>'browse_transactions','group'=>$groups['transactions'],'description'=>'list_of_all_transactions'],
            ['name'=>'read-transactions','display_name'=>'read_transactions','group'=>$groups['transactions'],'description'=>'read_the_selected_transaction'],
            ['name'=>'edit-transactions','display_name'=>'edit_transactions','group'=>$groups['transactions'],'description'=>'edit_the_selected_transaction'],
            ['name'=>'add-transactions','display_name'=>'add_transactions','group'=>$groups['transactions'],'description'=>'add_new_transaction'],
            ['name'=>'delete-transactions','display_name'=>'delete_transactions','group'=>$groups['transactions'],'description'=>'delete_the_selected_transaction'],

            // DEVICES
            ['name'=>'browse-devices','display_name'=>'browse_devices','group'=>$groups['devices'],'description'=>'list_of_all_devices'],
            ['name'=>'read-devices','display_name'=>'read_devices','group'=>$groups['devices'],'description'=>'read_the_selected_device'],
            ['name'=>'edit-devices','display_name'=>'edit_devices','group'=>$groups['devices'],'description'=>'edit_the_selected_device'],
            ['name'=>'add-devices','display_name'=>'add_devices','group'=>$groups['devices'],'description'=>'add_new_device'],
            ['name'=>'delete-devices','display_name'=>'delete_devices','group'=>$groups['devices'],'description'=>'delete_the_selected_device'],

            // SENSORS
            ['name'=>'browse-sensors','display_name'=>'browse_sensors','group'=>$groups['sensors'],'description'=>'list_of_all_sensors'],
            ['name'=>'read-sensors','display_name'=>'read_sensors','group'=>$groups['sensors'],'description'=>'read_the_selected_sensor'],
            ['name'=>'edit-sensors','display_name'=>'edit_sensors','group'=>$groups['sensors'],'description'=>'edit_the_selected_sensor'],
            ['name'=>'add-sensors','display_name'=>'add_sensors','group'=>$groups['sensors'],'description'=>'add_new_sensor'],
            ['name'=>'delete-sensors','display_name'=>'delete_sensors','group'=>$groups['sensors'],'description'=>'delete_the_selected_sensor'],

            // READINGS
            ['name'=>'browse-readings','display_name'=>'browse_readings','group'=>$groups['readings'],'description'=>'list_of_all_readings'],
            ['name'=>'read-readings','display_name'=>'read_readings','group'=>$groups['readings'],'description'=>'read_the_selected_reading'],
            ['name'=>'edit-readings','display_name'=>'edit_readings','group'=>$groups['readings'],'description'=>'edit_the_selected_reading'],
            ['name'=>'add-readings','display_name'=>'add_readings','group'=>$groups['readings'],'description'=>'add_new_reading'],
            ['name'=>'delete-readings','display_name'=>'delete_readings','group'=>$groups['readings'],'description'=>'delete_the_selected_reading'],

            // ALERTS
            ['name'=>'browse-alerts','display_name'=>'browse_alerts','group'=>$groups['alerts'],'description'=>'list_of_all_alerts'],
            ['name'=>'read-alerts','display_name'=>'read_alerts','group'=>$groups['alerts'],'description'=>'read_the_selected_alert'],
            ['name'=>'edit-alerts','display_name'=>'edit_alerts','group'=>$groups['alerts'],'description'=>'edit_the_selected_alert'],
            ['name'=>'add-alerts','display_name'=>'add_alerts','group'=>$groups['alerts'],'description'=>'add_new_alert'],
            ['name'=>'delete-alerts','display_name'=>'delete_alerts','group'=>$groups['alerts'],'description'=>'delete_the_selected_alert'],

            // ALERT RULES
            ['name'=>'browse-alert-rules','display_name'=>'browse_alert_rules','group'=>$groups['alert-rules'],'description'=>'list_of_all_alert_rules'],
            ['name'=>'read-alert-rules','display_name'=>'read_alert_rules','group'=>$groups['alert-rules'],'description'=>'read_the_selected_alert_rule'],
            ['name'=>'edit-alert-rules','display_name'=>'edit_alert_rules','group'=>$groups['alert-rules'],'description'=>'edit_the_selected_alert_rule'],
            ['name'=>'add-alert-rules','display_name'=>'add_alert_rules','group'=>$groups['alert-rules'],'description'=>'add_new_alert_rule'],
            ['name'=>'delete-alert-rules','display_name'=>'delete_alert_rules','group'=>$groups['alert-rules'],'description'=>'delete_the_selected_alert_rule'],

            // INVENTORY ITEMS
            ['name'=>'browse-inventory-items','display_name'=>'browse_inventory_items','group'=>$groups['inventory-items'],'description'=>'list_of_all_inventory_items'],
            ['name'=>'read-inventory-items','display_name'=>'read_inventory_items','group'=>$groups['inventory-items'],'description'=>'read_the_selected_inventory_item'],
            ['name'=>'edit-inventory-items','display_name'=>'edit_inventory_items','group'=>$groups['inventory-items'],'description'=>'edit_the_selected_inventory_item'],
            ['name'=>'add-inventory-items','display_name'=>'add_inventory_items','group'=>$groups['inventory-items'],'description'=>'add_new_inventory_item'],
            ['name'=>'delete-inventory-items','display_name'=>'delete_inventory_items','group'=>$groups['inventory-items'],'description'=>'delete_the_selected_inventory_item'],

            // INVENTORY MOVEMENTS
            ['name'=>'browse-inventory-movements','display_name'=>'browse_inventory_movements','group'=>$groups['inventory-movements'],'description'=>'list_of_all_inventory_movements'],
            ['name'=>'read-inventory-movements','display_name'=>'read_inventory_movements','group'=>$groups['inventory-movements'],'description'=>'read_the_selected_inventory_movement'],
            ['name'=>'edit-inventory-movements','display_name'=>'edit_inventory_movements','group'=>$groups['inventory-movements'],'description'=>'edit_the_selected_inventory_movement'],
            ['name'=>'add-inventory-movements','display_name'=>'add_inventory_movements','group'=>$groups['inventory-movements'],'description'=>'add_new_inventory_movement'],
            ['name'=>'delete-inventory-movements','display_name'=>'delete_inventory_movements','group'=>$groups['inventory-movements'],'description'=>'delete_the_selected_inventory_movement'],

            // FARMS OWNER
            ['name'=>'browse-farms','display_name'=>'browse_farms','group'=>$groups['farms'],'description'=>'list_of_all_farms'],
            ['name'=>'read-farms','display_name'=>'read_farms','group'=>$groups['farms'],'description'=>'read_the_selected_farm'],
            ['name'=>'edit-farms','display_name'=>'edit_farms','group'=>$groups['farms'],'description'=>'edit_the_selected_farm'],
            ['name'=>'add-farms','display_name'=>'add_farms','group'=>$groups['farms'],'description'=>'add_new_farm'],
            ['name'=>'delete-farms','display_name'=>'delete_farms','group'=>$groups['farms'],'description'=>'delete_the_selected_farm'],

            // Workflow Template Types
            ['name'=>'browse-workflow-template-types','display_name'=>'browse_workflow_template_types','group'=>$groups['workflow-template-types'],'description'=>'list_of_all_workflow_template_types'],
            ['name'=>'read-workflow-template-types','display_name'=>'read_workflow_template_types','group'=>$groups['workflow-template-types'],'description'=>'read_the_selected_workflow_template_type'],
            ['name'=>'edit-workflow-template-types','display_name'=>'edit_workflow_template_types','group'=>$groups['workflow-template-types'],'description'=>'edit_the_selected_workflow_template_type'],
            ['name'=>'add-workflow-template-types','display_name'=>'add_workflow_template_types','group'=>$groups['workflow-template-types'],'description'=>'add_new_workflow_template_type'],
            ['name'=>'delete-workflow-template-types','display_name'=>'delete_workflow_template_types','group'=>$groups['workflow-template-types'],'description'=>'delete_the_selected_workflow_template_type'],

            // Workflow Templates
            ['name'=>'browse-workflow-templates','display_name'=>'browse_workflow_templates','group'=>$groups['workflow-templates'],'description'=>'list_of_all_workflow_templates'],
            ['name'=>'read-workflow-templates','display_name'=>'read_workflow_templates','group'=>$groups['workflow-templates'],'description'=>'read_the_selected_workflow_template'],
            ['name'=>'edit-workflow-templates','display_name'=>'edit_workflow_templates','group'=>$groups['workflow-templates'],'description'=>'edit_the_selected_workflow_template'],
            ['name'=>'add-workflow-templates','display_name'=>'add_workflow_templates','group'=>$groups['workflow-templates'],'description'=>'add_new_workflow_template'],
            ['name'=>'delete-workflow-templates','display_name'=>'delete_workflow_templates','group'=>$groups['workflow-templates'],'description'=>'delete_the_selected_workflow_template'],

            // Bot Types
            ['name'=>'browse-bot-types','display_name'=>'browse_bot_types','group'=>$groups['bot-types'],'description'=>'list_of_all_bot_types'],
            ['name'=>'read-bot-types','display_name'=>'read_bot_types','group'=>$groups['bot-types'],'description'=>'read_the_selected_bot_type'],
            ['name'=>'edit-bot-types','display_name'=>'edit_bot_types','group'=>$groups['bot-types'],'description'=>'edit_the_selected_bot_type'],
            ['name'=>'add-bot-types','display_name'=>'add_bot_types','group'=>$groups['bot-types'],'description'=>'add_new_bot_type'],
            ['name'=>'delete-bot-types','display_name'=>'delete_bot_types','group'=>$groups['bot-types'],'description'=>'delete_the_selected_bot_type'],

            // Bots
            ['name'=>'browse-bots','display_name'=>'browse_bots','group'=>$groups['bots'],'description'=>'list_of_all_bots'],
            ['name'=>'read-bots','display_name'=>'read_bots','group'=>$groups['bots'],'description'=>'read_the_selected_bot'],
            ['name'=>'edit-bots','display_name'=>'edit_bots','group'=>$groups['bots'],'description'=>'edit_the_selected_bot'],
            ['name'=>'add-bots','display_name'=>'add_bots','group'=>$groups['bots'],'description'=>'add_new_bot'],
            ['name'=>'delete-bots','display_name'=>'delete_bots','group'=>$groups['bots'],'description'=>'delete_the_selected_bot'],

            // Bookings
            ['name'=>'browse-bookings','display_name'=>'browse_bookings','group'=>$groups['bookings'],'description'=>'list_of_all_bookings'],
            ['name'=>'read-bookings','display_name'=>'read_bookings','group'=>$groups['bookings'],'description'=>'read_the_selected_booking'],
            ['name'=>'edit-bookings','display_name'=>'edit_bookings','group'=>$groups['bookings'],'description'=>'edit_the_selected_booking'],
            ['name'=>'add-bookings','display_name'=>'add_bookings','group'=>$groups['bookings'],'description'=>'add_new_booking'],
            ['name'=>'delete-bookings','display_name'=>'delete_bookings','group'=>$groups['bookings'],'description'=>'delete_the_selected_booking'],

            // FAQs
            ['name'=>'browse-faqs','display_name'=>'browse_faqs','group'=>$groups['faqs'],'description'=>'list_of_all_faqs'],
            ['name'=>'read-faqs','display_name'=>'read_faqs','group'=>$groups['faqs'],'description'=>'read_the_selected_faq'],
            ['name'=>'edit-faqs','display_name'=>'edit_faqs','group'=>$groups['faqs'],'description'=>'edit_the_selected_faq'],
            ['name'=>'add-faqs','display_name'=>'add_faqs','group'=>$groups['faqs'],'description'=>'add_new_faq'],
            ['name'=>'delete-faqs','display_name'=>'delete_faqs','group'=>$groups['faqs'],'description'=>'delete_the_selected_faq'],

            // PRODUCTS
            ['name' => 'browse-products', 'display_name' => 'browse_products', 'group' => $groups['products'], 'description' => 'browse_products'],
            ['name' => 'read-products', 'display_name' => 'read_products', 'group' => $groups['products'], 'description' => 'read_products'],
            ['name' => 'edit-products', 'display_name' => 'edit_products', 'group' => $groups['products'], 'description' => 'edit_products'],
            ['name' => 'add-products', 'display_name' => 'add_products', 'group' => $groups['products'], 'description' => 'add_products'],
            ['name' => 'delete-products', 'display_name' => 'delete_products', 'group' => $groups['products'], 'description' => 'delete_products'],

            ['name' => 'browse-product-digitals', 'display_name' => 'browse_product_digitals', 'group' => $groups['product-digitals'], 'description' => 'browse_product_digitals'],
            ['name' => 'read-product-digitals', 'display_name' => 'read_product_digitals', 'group' => $groups['product-digitals'], 'description' => 'read_product_digitals'],
            ['name' => 'edit-product-digitals', 'display_name' => 'edit_product_digitals', 'group' => $groups['product-digitals'], 'description' => 'edit_product_digitals'],
            ['name' => 'add-product-digitals', 'display_name' => 'add_product_digitals', 'group' => $groups['product-digitals'], 'description' => 'add_product_digitals'],
            ['name' => 'delete-product-digitals', 'display_name' => 'delete_product_digitals', 'group' => $groups['product-digitals'], 'description' => 'delete_product_digitals'],

            ['name' => 'browse-product-physicals', 'display_name' => 'browse_product_physicals', 'group' => $groups['product-physicals'], 'description' => 'browse_product_physicals'],
            ['name' => 'read-product-physicals', 'display_name' => 'read_product_physicals', 'group' => $groups['product-physicals'], 'description' => 'read_product_physicals'],
            ['name' => 'edit-product-physicals', 'display_name' => 'edit_product_physicals', 'group' => $groups['product-physicals'], 'description' => 'edit_product_physicals'],
            ['name' => 'add-product-physicals', 'display_name' => 'add_product_physicals', 'group' => $groups['product-physicals'], 'description' => 'add_product_physicals'],
            ['name' => 'delete-product-physicals', 'display_name' => 'delete_product_physicals', 'group' => $groups['product-physicals'], 'description' => 'delete_product_physicals'],

            ['name' => 'browse-product-appointments', 'display_name' => 'browse_product_appointments', 'group' => $groups['product-appointments'], 'description' => 'browse_product_appointments'],
            ['name' => 'read-product-appointments', 'display_name' => 'read_product_appointments', 'group' => $groups['product-appointments'], 'description' => 'read_product_appointments'],
            ['name' => 'edit-product-appointments', 'display_name' => 'edit_product_appointments', 'group' => $groups['product-appointments'], 'description' => 'edit_product_appointments'],
            ['name' => 'add-product-appointments', 'display_name' => 'add_product_appointments', 'group' => $groups['product-appointments'], 'description' => 'add_product_appointments'],
            ['name' => 'delete-product-appointments', 'display_name' => 'delete_product_appointments', 'group' => $groups['product-appointments'], 'description' => 'delete_product_appointments'],

            // Companies
            ['name' => 'browse-companies', 'display_name' => 'browse_companies', 'group' => $groups['companies'], 'description' => 'browse_companies'],
            ['name' => 'read-companies', 'display_name' => 'read_companies', 'group' => $groups['companies'], 'description' => 'read_companies'],
            ['name' => 'edit-companies', 'display_name' => 'edit_companies', 'group' => $groups['companies'], 'description' => 'edit_companies'],
            ['name' => 'add-companies', 'display_name' => 'add_companies', 'group' => $groups['companies'], 'description' => 'add_companies'],
            ['name' => 'delete-companies', 'display_name' => 'delete_companies', 'group' => $groups['companies'], 'description' => 'delete_companies'],

            ['name' => 'browse-brands', 'display_name' => 'browse_brands', 'group' => $groups['brands'], 'description' => 'browse_brands'],
            ['name' => 'read-brands', 'display_name' => 'read_brands', 'group' => $groups['brands'], 'description' => 'read_brands'],
            ['name' => 'edit-brands', 'display_name' => 'edit_brands', 'group' => $groups['brands'], 'description' => 'edit_brands'],
            ['name' => 'add-brands', 'display_name' => 'add_brands', 'group' => $groups['brands'], 'description' => 'add_brands'],
            ['name' => 'delete-brands', 'display_name' => 'delete_brands', 'group' => $groups['brands'], 'description' => 'delete_brands'],

            ['name' => 'browse-brand-categories', 'display_name' => 'browse_brand_categories', 'group' => $groups['brand-categories'], 'description' => 'browse_brand_categories'],
            ['name' => 'read-brand-categories', 'display_name' => 'read_brand_categories', 'group' => $groups['brand-categories'], 'description' => 'read_brand_categories'],
            ['name' => 'edit-brand-categories', 'display_name' => 'edit_brand_categories', 'group' => $groups['brand-categories'], 'description' => 'edit_brand_categories'],
            ['name' => 'add-brand-categories', 'display_name' => 'add_brand_categories', 'group' => $groups['brand-categories'], 'description' => 'add_brand_categories'],
            ['name' => 'delete-brand-categories', 'display_name' => 'delete_brand_categories', 'group' => $groups['brand-categories'], 'description' => 'delete_brand_categories'],
        ]);
    }
}
