<?php
namespace Database\Seeders\UserProfiles;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class UserProfileSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $userProfiles = [
            [
                'user_id' => 2,
                'position' => 'Software Engineer',
                'organization_id' => 3,
                'company_id' => 1,
                'bio' => "Experienced Software Engineer with 5+ years delivering scalable web and mobile apps. I work across the stack to turn ideas into reliable, maintainable products.

                I use Laravel for robust, secure backends and Vue/React for fast, intuitive front-ends. When mobile is the right fit, I ship with Flutter. On the infra side, I’m comfortable with AWS and modern CI/CD.

                Lately I’ve been building AI-powered content automation: stitching together multiple AI APIs, n8n workflows, and Supabase to make processes faster, cheaper, and more consistent.

                My focus is simple: streamline workflows, improve operational efficiency, and ship business-ready solutions that move the needle.",
                'years_of_experience' => 5,
                'education' => 'Bachelor of Computer Science, University of Technology',
                'certification' => 'AWS Certified Developer, Scrum Master',
                'linkedin_url' => 'https://linkedin.com/in/samsulhadi-ss',
                'threads_url' => 'https://www.threads.com/@samsulhadi_ss',
                'twitter_url' => 'https://x.com/samsulhadi_ss',
                'facebook_url' => 'https://www.facebook.com/samsul.hadi.796',
                'youtube_url' => 'https://www.youtube.com/@samsulhadi_ss',
                'tiktok_url' => 'https://www.tiktok.com/@samsulhadi_ss',
                'instagram_url' => 'https://www.instagram.com/samsulhadi_ss/',
                'medium_url' => 'https://medium.com/@samsulhadi_ss',
                'github_url' => 'https://github.com/samsul97',
            ],
            [
                'user_id' => 3,
                'position' => 'Student | Backend | Linux Enthusiast',
                'organization_id' => 3,
                'company_id' => null,
                'bio' => null,
                'years_of_experience' => 3,
                'education' => 'Sumatra Institute of Technology',
                'certification' => 'Apple Developer Academy, Machine Learning, Python',
                'linkedin_url' => 'https://www.linkedin.com/in/syuhadarantisi/',
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
            [
                'user_id' => 4,
                'position' => 'Frontend Developer',
                'organization_id' => 3,
                'company_id' => null,
                'bio' => null,
                'years_of_experience' => 3,
                'education' => 'Unindra',
                'certification' => 'Algooritma, Html Css, Front-End JavaScript',
                'linkedin_url' => 'https://www.linkedin.com/in/erwin-haryono-45a627144/',
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
            [
                'user_id' => 5,
                'position' => 'Program Manager',
                'organization_id' => 2,
                'company_id' => null,
                'bio' => null,
                'years_of_experience' => 5,
                'education' => 'STIKS Tarakanita Bachelors degree, Business/Corporate Communications',
                'certification' => 'Social Media, CRM, Communication',
                'linkedin_url' => 'https://www.linkedin.com/in/albertina-suryaning-686484156/',
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
            [
                'user_id' => 6,
                'position' => 'HR',
                'organization_id' => 3,
                'company_id' => null,
                'bio' => null,
                'years_of_experience' => 5,
                'education' => 'UIN Jakarta',
                'certification' => 'Hardware, Computer Networking, Software Dev',
                'linkedin_url' => 'https://www.linkedin.com/in/indra-prasetyo-a83256177/',
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
            [
                'user_id' => 7,
                'position' => 'Software Engineer',
                'organization_id' => 3,
                'company_id' => null,
                'bio' => null,
                'years_of_experience' => 5,
                'education' => null,
                'certification' => 'PHP, Linux Server, Database',
                'linkedin_url' => 'https://www.linkedin.com/in/muhammad-ujang-396821108/',
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
            [
                'user_id' => 8,
                'position' => 'Digital Marketing',
                'organization_id' => 2,
                'company_id' => null,
                'bio' => null,
                'years_of_experience' => 3,
                'education' => 'Diploma in Digital Marketing, IDN Academy',
                'certification' => 'Google Ads Certified',
                'linkedin_url' => 'https://linkedin.com/in/humamafifi',
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
            [
                'user_id' => 9,
                'position' => 'Designer',
                'organization_id' => 2,
                'company_id' => null,
                'bio' => null,
                'years_of_experience' => 4,
                'education' => 'Visual Communication Design, Universitas Indonesia',
                'certification' => 'Adobe Certified Expert (ACE)',
                'linkedin_url' => 'https://linkedin.com/in/fahrihusaini',
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
            [
                'user_id' => 10,
                'position' => 'Editor',
                'organization_id' => 2,
                'company_id' => null,
                'bio' => null,
                'years_of_experience' => 6,
                'education' => 'Broadcasting, Universitas Mercu Buana',
                'certification' => 'Final Cut Pro Certified',
                'linkedin_url' => 'https://linkedin.com/in/nizomudin',
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
            [
                'user_id' => 11,
                'position' => 'Accountant',
                'organization_id' => 3,
                'company_id' => 4,
                'bio' => null,
                'years_of_experience' => 5,
                'education' => 'Unpam, Accountant',
                'certification' => null,
                'linkedin_url' => null,
                'threads_url' => null,
                'twitter_url' => null,
                'facebook_url' => null,
                'youtube_url' => null,
                'tiktok_url' => null,
                'instagram_url' => null,
                'medium_url' => null,
                'github_url' => null,
            ],
        ];

        foreach ($userProfiles as &$instructor) {
            $instructor['created_at'] = $now;
            $instructor['updated_at'] = $now;
        }

        DB::table('user_profiles')->insert($userProfiles);
    }
}
